insert into comments (id, user_id, resource_id, content) values (1, 2, 24, 'in hac habitasse platea dictumst aliquam augue');
insert into comments (id, user_id, resource_id, content) values (2, 3, 33, 'donec ut mauris eget massa tempor convallis');
insert into comments (id, user_id, resource_id, content) values (3, 2, 1, 'amet sem fusce consequat');
insert into comments (id, user_id, resource_id, content) values (4, 5, 28, 'sit amet diam in magna bibendum imperdiet nullam orci');
insert into comments (id, user_id, resource_id, content) values (5, 3, 36, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into comments (id, user_id, resource_id, content) values (6, 2, 22, 'nisi volutpat eleifend donec ut dolor morbi vel lectus');
insert into comments (id, user_id, resource_id, content) values (7, 1, 38, 'phasellus in felis donec semper sapien a libero nam dui');
insert into comments (id, user_id, resource_id, content) values (8, 4, 26, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer');
insert into comments (id, user_id, resource_id, content) values (9, 3, 3, 'ipsum primis in faucibus');
insert into comments (id, user_id, resource_id, content) values (10, 5, 27, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into comments (id, user_id, resource_id, content) values (11, 2, 11, 'elementum ligula vehicula');
insert into comments (id, user_id, resource_id, content) values (12, 4, 11, 'eu est congue');
insert into comments (id, user_id, resource_id, content) values (13, 3, 19, 'erat nulla tempus vivamus in felis eu');
insert into comments (id, user_id, resource_id, content) values (14, 1, 21, 'sed vel enim sit amet nunc viverra dapibus nulla');
insert into comments (id, user_id, resource_id, content) values (15, 3, 17, 'fusce congue diam id ornare imperdiet sapien urna');
insert into comments (id, user_id, resource_id, content) values (16, 3, 43, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into comments (id, user_id, resource_id, content) values (17, 5, 5, 'placerat praesent blandit nam nulla integer pede justo');
insert into comments (id, user_id, resource_id, content) values (18, 5, 42, 'cras in purus eu magna vulputate luctus');
insert into comments (id, user_id, resource_id, content) values (19, 2, 41, 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into comments (id, user_id, resource_id, content) values (20, 4, 45, 'suspendisse ornare consequat lectus in est risus auctor sed tristique');
insert into comments (id, user_id, resource_id, content) values (21, 5, 37, 'at turpis donec posuere metus vitae ipsum aliquam non');
insert into comments (id, user_id, resource_id, content) values (22, 4, 6, 'lobortis vel dapibus');
insert into comments (id, user_id, resource_id, content) values (23, 1, 41, 'dolor sit amet consectetuer adipiscing elit proin');
insert into comments (id, user_id, resource_id, content) values (24, 2, 3, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id');
insert into comments (id, user_id, resource_id, content) values (25, 3, 14, 'lobortis est phasellus sit amet erat nulla tempus vivamus in');
insert into comments (id, user_id, resource_id, content) values (26, 5, 4, 'ultrices mattis odio donec vitae nisi nam ultrices');
insert into comments (id, user_id, resource_id, content) values (27, 3, 31, 'dui vel sem sed sagittis nam congue risus');
insert into comments (id, user_id, resource_id, content) values (28, 3, 20, 'mus etiam vel augue vestibulum');
insert into comments (id, user_id, resource_id, content) values (29, 5, 8, 'pharetra magna ac');
insert into comments (id, user_id, resource_id, content) values (30, 2, 45, 'pellentesque viverra pede ac diam');
insert into comments (id, user_id, resource_id, content) values (31, 3, 14, 'diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into comments (id, user_id, resource_id, content) values (32, 5, 13, 'hac habitasse platea dictumst morbi vestibulum');
insert into comments (id, user_id, resource_id, content) values (33, 3, 36, 'lobortis vel dapibus at diam nam tristique tortor');
insert into comments (id, user_id, resource_id, content) values (34, 2, 11, 'mauris ullamcorper purus');
insert into comments (id, user_id, resource_id, content) values (35, 5, 32, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci');
insert into comments (id, user_id, resource_id, content) values (36, 5, 8, 'enim leo rhoncus sed');
insert into comments (id, user_id, resource_id, content) values (37, 1, 41, 'libero quis orci nullam');
insert into comments (id, user_id, resource_id, content) values (38, 1, 15, 'imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into comments (id, user_id, resource_id, content) values (39, 2, 9, 'ut tellus nulla ut erat id mauris vulputate');
insert into comments (id, user_id, resource_id, content) values (40, 3, 32, 'turpis sed ante vivamus');
insert into comments (id, user_id, resource_id, content) values (41, 3, 13, 'quisque ut erat curabitur gravida nisi');
insert into comments (id, user_id, resource_id, content) values (42, 3, 5, 'malesuada in imperdiet et commodo vulputate justo');
insert into comments (id, user_id, resource_id, content) values (43, 3, 31, 'eget orci vehicula condimentum curabitur');
insert into comments (id, user_id, resource_id, content) values (44, 2, 11, 'iaculis diam erat');
insert into comments (id, user_id, resource_id, content) values (45, 2, 43, 'sed vel enim sit amet nunc viverra');
insert into comments (id, user_id, resource_id, content) values (46, 5, 15, 'duis bibendum felis sed');
insert into comments (id, user_id, resource_id, content) values (47, 2, 3, 'ut erat id');
insert into comments (id, user_id, resource_id, content) values (48, 3, 16, 'nulla nunc purus phasellus in felis donec');
insert into comments (id, user_id, resource_id, content) values (49, 2, 40, 'ipsum integer a nibh in quis');
insert into comments (id, user_id, resource_id, content) values (50, 3, 34, 'gravida sem praesent id massa');
insert into comments (id, user_id, resource_id, content) values (51, 1, 14, 'dui proin leo odio porttitor');
insert into comments (id, user_id, resource_id, content) values (52, 1, 9, 'nunc purus phasellus');
insert into comments (id, user_id, resource_id, content) values (53, 3, 11, 'enim leo rhoncus sed vestibulum sit amet');
insert into comments (id, user_id, resource_id, content) values (54, 2, 4, 'nec molestie sed justo pellentesque viverra pede ac diam cras');
insert into comments (id, user_id, resource_id, content) values (55, 4, 27, 'venenatis tristique fusce congue diam id');
insert into comments (id, user_id, resource_id, content) values (56, 2, 38, 'orci luctus et ultrices posuere cubilia curae');
insert into comments (id, user_id, resource_id, content) values (57, 1, 21, 'primis in faucibus orci luctus');
insert into comments (id, user_id, resource_id, content) values (58, 5, 42, 'turpis nec euismod scelerisque');
insert into comments (id, user_id, resource_id, content) values (59, 4, 5, 'sit amet consectetuer adipiscing elit proin interdum mauris');
insert into comments (id, user_id, resource_id, content) values (60, 4, 45, 'phasellus in felis donec semper');
insert into comments (id, user_id, resource_id, content) values (61, 4, 18, 'at velit eu est congue');
insert into comments (id, user_id, resource_id, content) values (62, 3, 5, 'porta volutpat erat quisque erat eros');
