insert into comments (user_id, resource_id, content) values (2, 24, 'in hac habitasse platea dictumst aliquam augue');
insert into comments (user_id, resource_id, content) values (3, 33, 'donec ut mauris eget massa tempor convallis');
insert into comments (user_id, resource_id, content) values (2, 1, 'amet sem fusce consequat');
insert into comments (user_id, resource_id, content) values (5, 28, 'sit amet diam in magna bibendum imperdiet nullam orci');
insert into comments (user_id, resource_id, content) values (3, 36, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into comments (user_id, resource_id, content) values (2, 22, 'nisi volutpat eleifend donec ut dolor morbi vel lectus');
insert into comments (user_id, resource_id, content) values (1, 38, 'phasellus in felis donec semper sapien a libero nam dui');
insert into comments (user_id, resource_id, content) values (4, 26, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer');
insert into comments (user_id, resource_id, content) values (3, 3, 'ipsum primis in faucibus');
insert into comments (user_id, resource_id, content) values (5, 27, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into comments (user_id, resource_id, content) values (2, 11, 'elementum ligula vehicula');
insert into comments (user_id, resource_id, content) values (4, 11, 'eu est congue');
insert into comments (user_id, resource_id, content) values (3, 19, 'erat nulla tempus vivamus in felis eu');
insert into comments (user_id, resource_id, content) values (1, 21, 'sed vel enim sit amet nunc viverra dapibus nulla');
insert into comments (user_id, resource_id, content) values (3, 17, 'fusce congue diam id ornare imperdiet sapien urna');
insert into comments (user_id, resource_id, content) values (3, 43, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into comments (user_id, resource_id, content) values (5, 5, 'placerat praesent blandit nam nulla integer pede justo');
insert into comments (user_id, resource_id, content) values (5, 42, 'cras in purus eu magna vulputate luctus');
insert into comments (user_id, resource_id, content) values (2, 41, 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into comments (user_id, resource_id, content) values (4, 45, 'suspendisse ornare consequat lectus in est risus auctor sed tristique');
insert into comments (user_id, resource_id, content) values (5, 37, 'at turpis donec posuere metus vitae ipsum aliquam non');
insert into comments (user_id, resource_id, content) values (4, 6, 'lobortis vel dapibus');
insert into comments (user_id, resource_id, content) values (1, 41, 'dolor sit amet consectetuer adipiscing elit proin');
insert into comments (user_id, resource_id, content) values (2, 3, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id');
insert into comments (user_id, resource_id, content) values (3, 14, 'lobortis est phasellus sit amet erat nulla tempus vivamus in');
insert into comments (user_id, resource_id, content) values (5, 4, 'ultrices mattis odio donec vitae nisi nam ultrices');
insert into comments (user_id, resource_id, content) values (3, 31, 'dui vel sem sed sagittis nam congue risus');
insert into comments (user_id, resource_id, content) values (3, 20, 'mus etiam vel augue vestibulum');
insert into comments (user_id, resource_id, content) values (5, 8, 'pharetra magna ac');
insert into comments (user_id, resource_id, content) values (2, 45, 'pellentesque viverra pede ac diam');
insert into comments (user_id, resource_id, content) values (3, 14, 'diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into comments (user_id, resource_id, content) values (5, 13, 'hac habitasse platea dictumst morbi vestibulum');
insert into comments (user_id, resource_id, content) values (3, 36, 'lobortis vel dapibus at diam nam tristique tortor');
insert into comments (user_id, resource_id, content) values (2, 11, 'mauris ullamcorper purus');
insert into comments (user_id, resource_id, content) values (5, 32, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci');
insert into comments (user_id, resource_id, content) values (5, 8, 'enim leo rhoncus sed');
insert into comments (user_id, resource_id, content) values (1, 41, 'libero quis orci nullam');
insert into comments (user_id, resource_id, content) values (1, 15, 'imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into comments (user_id, resource_id, content) values (2, 9, 'ut tellus nulla ut erat id mauris vulputate');
insert into comments (user_id, resource_id, content) values (3, 32, 'turpis sed ante vivamus');
insert into comments (user_id, resource_id, content) values (3, 13, 'quisque ut erat curabitur gravida nisi');
insert into comments (user_id, resource_id, content) values (3, 5, 'malesuada in imperdiet et commodo vulputate justo');
insert into comments (user_id, resource_id, content) values (3, 31, 'eget orci vehicula condimentum curabitur');
insert into comments (user_id, resource_id, content) values (2, 11, 'iaculis diam erat');
insert into comments (user_id, resource_id, content) values (2, 43, 'sed vel enim sit amet nunc viverra');
insert into comments (user_id, resource_id, content) values (5, 15, 'duis bibendum felis sed');
insert into comments (user_id, resource_id, content) values (2, 3, 'ut erat id');
insert into comments (user_id, resource_id, content) values (3, 16, 'nulla nunc purus phasellus in felis donec');
insert into comments (user_id, resource_id, content) values (2, 40, 'ipsum integer a nibh in quis');
insert into comments (user_id, resource_id, content) values (3, 34, 'gravida sem praesent id massa');
insert into comments (user_id, resource_id, content) values (1, 14, 'dui proin leo odio porttitor');
insert into comments (user_id, resource_id, content) values (1, 9, 'nunc purus phasellus');
insert into comments (user_id, resource_id, content) values (3, 11, 'enim leo rhoncus sed vestibulum sit amet');
insert into comments (user_id, resource_id, content) values (2, 4, 'nec molestie sed justo pellentesque viverra pede ac diam cras');
insert into comments (user_id, resource_id, content) values (4, 27, 'venenatis tristique fusce congue diam id');
insert into comments (user_id, resource_id, content) values (2, 38, 'orci luctus et ultrices posuere cubilia curae');
insert into comments (user_id, resource_id, content) values (1, 21, 'primis in faucibus orci luctus');
insert into comments (user_id, resource_id, content) values (5, 42, 'turpis nec euismod scelerisque');
insert into comments (user_id, resource_id, content) values (4, 5, 'sit amet consectetuer adipiscing elit proin interdum mauris');
insert into comments (user_id, resource_id, content) values (4, 45, 'phasellus in felis donec semper');
insert into comments (user_id, resource_id, content) values (4, 18, 'at velit eu est congue');
insert into comments (user_id, resource_id, content) values (3, 5, 'porta volutpat erat quisque erat eros');
